
package com.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculatorImplementsService", targetNamespace = "http://service.webservices.com/", wsdlLocation = "http://localhost/8085/service/calculator?wsdl")
public class CalculatorImplementsService
    extends Service
{

    private final static URL CALCULATORIMPLEMENTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORIMPLEMENTSSERVICE_EXCEPTION;
    private final static QName CALCULATORIMPLEMENTSSERVICE_QNAME = new QName("http://service.webservices.com/", "CalculatorImplementsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/8085/service/calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORIMPLEMENTSSERVICE_WSDL_LOCATION = url;
        CALCULATORIMPLEMENTSSERVICE_EXCEPTION = e;
    }

    public CalculatorImplementsService() {
        super(__getWsdlLocation(), CALCULATORIMPLEMENTSSERVICE_QNAME);
    }

    public CalculatorImplementsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORIMPLEMENTSSERVICE_QNAME, features);
    }

    public CalculatorImplementsService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORIMPLEMENTSSERVICE_QNAME);
    }

    public CalculatorImplementsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORIMPLEMENTSSERVICE_QNAME, features);
    }

    public CalculatorImplementsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorImplementsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorImplementsPort")
    public Calculator getCalculatorImplementsPort() {
        return super.getPort(new QName("http://service.webservices.com/", "CalculatorImplementsPort"), Calculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorImplementsPort")
    public Calculator getCalculatorImplementsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservices.com/", "CalculatorImplementsPort"), Calculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORIMPLEMENTSSERVICE_EXCEPTION!= null) {
            throw CALCULATORIMPLEMENTSSERVICE_EXCEPTION;
        }
        return CALCULATORIMPLEMENTSSERVICE_WSDL_LOCATION;
    }

}
